[toolchain]
anchor_version = "0.30.0"

[programs.devnet]
solanapilot_registry = "Xo7TcdZwXZwU2S4em9r8Gn1L5L9ppmkqFLBpCXcuSPs"

[programs.localnet]
solanapilot_registry = "Xo7TcdZwXZwU2S4em9r8Gn1L5L9ppmkqFLBpCXcuSPs"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha --require ts-node/register tests/**/*.ts"
