[toolchain]
anchor_version = "0.30.0"

[programs.devnet]
solanapilot_registry = "Xo7TcdZwXZwU2S4em9r8Gn1L5L9ppmkqFLBpCXcuSPs"

[programs.localnet]
solanapilot_registry = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
build = "anchor build --program-name solanapilot_registry"
deploy-devnet = "anchor deploy --program-name solanapilot_registry"
test = "cargo test -- --nocapture"
